@extends('layouts.app')

@php
    $stats = [
        ['key' => 'total', 'label' => 'Total Reports', 'sub' => 'All reports received', 'tone' => 'primary'],
        ['key' => 'Unread', 'label' => 'New / Unread', 'sub' => 'Not opened yet', 'tone' => 'danger'],
        ['key' => 'Awaiting Reply', 'label' => 'Awaiting Reply', 'sub' => 'IATO expects a response', 'tone' => 'warning'],
        ['key' => 'Replied', 'label' => 'Replied', 'sub' => 'Responses sent', 'tone' => 'primary'],
    ];
@endphp

@section('title', 'iARIS — LAMP Office · Reports')
@section('page-title', 'Reports')
@section('page-subtitle', 'Reports received from IATO — view, download, and reply')

@section('content')
    {{-- Stat cards (numbers filled in by the script) --}}
    <div class="row row-cols-2 row-cols-xl-4 g-3 mb-4">
        @foreach ($stats as $stat)
            <div class="col">
                <div class="card border-0 border-top border-3 border-{{ $stat['tone'] }} shadow-sm rounded-4 h-100">
                    <div class="card-body">
                        <div class="small fw-bold text-uppercase tracking-wide text-body-secondary mb-2">{{ $stat['label'] }}</div>
                        <div class="fs-3 fw-bold text-{{ $stat['tone'] === 'primary' ? 'body' : $stat['tone'] . '-emphasis' }}" data-stat="{{ $stat['key'] }}">0</div>
                        <div class="small text-body-secondary">{{ $stat['sub'] }}</div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>

    <div class="card border-0 shadow-sm rounded-4">
        {{-- Search, type, sort --}}
        <div class="d-flex flex-wrap align-items-center gap-2 px-4 py-3 border-bottom">
            <div class="input-group" style="max-width: 320px;">
                <span class="input-group-text bg-white text-body-secondary"><i class="bi bi-search"></i></span>
                <input type="search" class="form-control" id="search" placeholder="Search report title…" aria-label="Search reports">
            </div>
            <select class="form-select w-auto" id="typeFilter" aria-label="Filter by report type">
                <option value="">All Report Types</option>
                @foreach ($reportTypes as $type => $style)
                    <option>{{ $type }}</option>
                @endforeach
            </select>
            <select class="form-select w-auto" id="sort" aria-label="Sort">
                <option value="newest">Sort: Newest First</option>
                <option value="oldest">Sort: Oldest First</option>
                <option value="unread">Sort: Unread First</option>
            </select>
        </div>

        {{-- Status pills --}}
        <div class="d-flex flex-wrap align-items-center gap-2 px-4 py-3 border-bottom" id="statusPills">
            <span class="small fw-bold text-body-secondary me-1">Status:</span>
            <button type="button" class="btn btn-sm rounded-pill px-3 fw-semibold btn-primary" data-status="">All</button>
            @foreach ($reportStatuses as $status => $tone)
                <button type="button" class="btn btn-sm rounded-pill px-3 fw-semibold btn-outline-secondary" data-status="{{ $status }}">{{ $status }}</button>
            @endforeach
        </div>

        <div class="list-group list-group-flush" id="reportList"></div>
        <div class="text-center text-body-secondary py-5 d-none" id="noResults">
            <i class="bi bi-inbox fs-3 d-block mb-2"></i> No reports match your search or filters.
        </div>
        <div class="card-footer bg-white rounded-bottom-4 small text-body-secondary px-4 py-3" id="showingText"></div>
    </div>

    {{-- One report in the list, copied by the script --}}
    <template id="reportTemplate">
        <div class="list-group-item list-group-item-action d-flex flex-wrap flex-md-nowrap align-items-center gap-3 px-4 py-3" role="button" tabindex="0">
            {{-- Red dot = not opened yet --}}
            <span class="rounded-circle flex-shrink-0" style="width: 9px; height: 9px;" data-cell="dot"></span>
            <div class="icon-circle rounded-3 fs-5 d-flex align-items-center justify-content-center" data-cell="icon"><i class="bi"></i></div>
            <div class="flex-grow-1" style="min-width: 200px;">
                <div class="fw-bold" data-cell="title"></div>
                <div class="small text-body-secondary d-flex flex-wrap align-items-center gap-2">
                    <span>Sent by <b data-cell="sender"></b> (IATO Admin)</span>
                    <span>·</span>
                    <span data-cell="sent"></span>
                    <span data-cell="type"></span>
                </div>
            </div>
            <div class="d-flex align-items-center gap-2 ms-auto">
                <span data-cell="status"></span>
                {{-- TODO: download the real file once reports are generated by the backend --}}
                <button type="button" class="btn btn-sm btn-light border" disabled title="Download (coming soon)" aria-label="Download"><i class="bi bi-download"></i></button>
                <button type="button" class="btn btn-sm btn-primary fw-semibold text-nowrap" data-cell="reply"></button>
            </div>
        </div>
    </template>

    {{-- Report drawer: preview + reply thread. id="applicantDrawer" so the print rules work. --}}
    <div class="offcanvas offcanvas-end" tabindex="-1" id="applicantDrawer" aria-labelledby="drawerTitle" style="--bs-offcanvas-width: 600px;">
        <div class="offcanvas-header bg-iaris text-white align-items-start gap-3 p-4">
            <div class="flex-grow-1">
                <h2 class="offcanvas-title fs-5 fw-bold mb-2" id="drawerTitle"></h2>
                <div class="small text-white-50 d-flex flex-wrap gap-2 align-items-center">
                    <span id="drawerSender"></span><span>·</span><span id="drawerSent"></span>
                    <span class="badge rounded-pill bg-white text-body" id="drawerType"></span>
                </div>
            </div>
            <button type="button" class="btn-close btn-close-white no-print" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>

        <ul class="nav nav-underline px-4 border-bottom no-print" role="tablist">
            <li class="nav-item"><button class="nav-link active fw-bold py-3" data-bs-toggle="tab" data-bs-target="#tabPreview" type="button" role="tab">Report Preview</button></li>
            <li class="nav-item"><button class="nav-link fw-bold py-3" data-bs-toggle="tab" data-bs-target="#tabThread" type="button" role="tab" id="threadTab">Reply Thread</button></li>
        </ul>

        <div class="offcanvas-body tab-content p-4">
            <div class="tab-pane fade show active" id="tabPreview" role="tabpanel">
                <div class="rounded-3 border bg-body-tertiary p-3 mb-3">
                    <div class="fw-bold mb-3" id="previewTitle"></div>
                    <div class="row g-3 small mb-3">
                        <div class="col-6 col-sm-3"><div class="fw-bold text-uppercase text-body-secondary">Prepared by</div><div id="previewSender"></div></div>
                        <div class="col-6 col-sm-3"><div class="fw-bold text-uppercase text-body-secondary">Date sent</div><div id="previewDate"></div></div>
                        <div class="col-6 col-sm-3"><div class="fw-bold text-uppercase text-body-secondary">AY</div><div>{{ $academicYear }}</div></div>
                        <div class="col-6 col-sm-3"><div class="fw-bold text-uppercase text-body-secondary">Type</div><div id="previewType"></div></div>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-sm align-middle small mb-0 bg-white">
                            <thead>
                                <tr class="text-uppercase">
                                    <th class="text-body-secondary">Applicant</th>
                                    <th class="text-body-secondary">Scholarship (IATO)</th>
                                    <th class="text-body-secondary">LAMP Status</th>
                                    <th class="text-body-secondary">Note</th>
                                </tr>
                            </thead>
                            <tbody id="previewRows"></tbody>
                        </table>
                    </div>
                </div>
                <div class="d-flex flex-wrap gap-2 no-print">
                    <button type="button" class="btn btn-light border btn-sm" disabled title="Coming soon"><i class="bi bi-file-earmark-pdf text-danger me-1"></i> Download PDF</button>
                    <button type="button" class="btn btn-light border btn-sm" disabled title="Coming soon"><i class="bi bi-file-earmark-excel text-success me-1"></i> Download Excel</button>
                    <button type="button" class="btn btn-light border btn-sm" onclick="window.print()"><i class="bi bi-printer me-1"></i> Print</button>
                </div>
            </div>

            {{-- Messages: IATO on the left, LAMP on the right --}}
            <div class="tab-pane fade" id="tabThread" role="tabpanel">
                <div class="d-flex flex-column gap-3" id="thread"></div>
            </div>
        </div>

        {{-- Reply box --}}
        <form class="border-top p-3 no-print" id="replyForm" novalidate>
            <label for="replyText" class="visually-hidden">Reply to IATO Admin</label>
            <textarea class="form-control mb-2" id="replyText" rows="3" placeholder="Type your reply to IATO Admin…" required></textarea>
            <div class="d-flex justify-content-end gap-2">
                <button type="reset" class="btn btn-light border">Clear</button>
                <button type="submit" class="btn btn-primary fw-semibold"><i class="bi bi-send me-1"></i> Send Reply</button>
            </div>
        </form>
    </div>

    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div class="toast align-items-center border-0 text-bg-dark" id="lampToast" role="status" aria-live="polite">
            <div class="d-flex">
                <div class="toast-body" id="lampToastText"></div>
                <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        // Front end only: opening and replying change REPORTS in the browser until reload.
        // TODO: save "read" and replies through a backend route, and notify IATO.
        const REPORTS = @json($reports);
        const SCHOLARS = @json($scholars);
        const TYPES = @json($reportTypes);
        const STATUSES = @json($reportStatuses);
        const LAMP_BADGES = @json($lampBadges);

        const state = { search: '', type: '', status: '', sort: 'newest' };
        let openId = null;   // report shown in the drawer
        const byId = id => REPORTS.find(r => r.id === id);

        function setBadge(el, text, tone, icon) {
            el.className = `badge rounded-pill bg-${tone}-subtle text-${tone}-emphasis`;
            el.textContent = text;
            if (icon) {
                const i = document.createElement('i');
                i.className = `bi ${icon} me-1`;
                el.prepend(i);
            }
        }

        function toast(text) {
            document.getElementById('lampToastText').textContent = text;
            bootstrap.Toast.getOrCreateInstance(document.getElementById('lampToast')).show();
        }

        // ---- The list ----
        function render() {
            const count = status => REPORTS.filter(r => r.status === status).length;
            document.querySelectorAll('[data-stat]').forEach(el =>
                el.textContent = el.dataset.stat === 'total' ? REPORTS.length : count(el.dataset.stat));
            // Keep the sidebar's red number in step
            const navBadge = document.getElementById('navReportsBadge');
            if (navBadge) {
                navBadge.textContent = count('Unread');
                navBadge.classList.toggle('d-none', count('Unread') === 0);
            }

            const matches = REPORTS.filter(r =>
                (!state.type || r.type === state.type) &&
                (!state.status || r.status === state.status) &&
                r.title.toLowerCase().includes(state.search)
            ).sort({
                newest: (a, b) => b.sent.localeCompare(a.sent),
                oldest: (a, b) => a.sent.localeCompare(b.sent),
                unread: (a, b) => (b.status === 'Unread') - (a.status === 'Unread') || b.sent.localeCompare(a.sent),
            }[state.sort]);

            const template = document.getElementById('reportTemplate').content.firstElementChild;
            document.getElementById('reportList').replaceChildren(...matches.map(r => {
                const item = template.cloneNode(true);
                const cell = name => item.querySelector(`[data-cell="${name}"]`);
                const [tone, icon] = TYPES[r.type];
                const unread = r.status === 'Unread';
                item.dataset.id = r.id;
                if (unread) item.classList.add('bg-warning-subtle');
                cell('dot').classList.add(unread ? 'bg-danger' : 'bg-transparent');
                cell('icon').classList.add(`bg-${tone}-subtle`, `text-${tone}-emphasis`);
                cell('icon').firstElementChild.classList.add(icon);
                cell('title').textContent = r.title;
                cell('sender').textContent = r.sender;
                cell('sent').textContent = r.sent_label;
                setBadge(cell('type'), r.type, tone);
                setBadge(cell('status'), unread ? 'New' : r.status, STATUSES[r.status]);
                // "Reply" only when IATO is waiting for an answer
                cell('reply').innerHTML = r.status === 'Replied' ? '<i class="bi bi-chat-left-text me-1"></i> View Thread'
                    : r.needs_reply ? '<i class="bi bi-reply me-1"></i> Reply'
                    : '<i class="bi bi-eye me-1"></i> View';
                cell('reply').dataset.reply = r.id;
                return item;
            }));
            document.getElementById('noResults').classList.toggle('d-none', matches.length > 0);
            document.getElementById('showingText').textContent = `Showing ${matches.length} of ${REPORTS.length} reports`;
        }

        const setFilter = (key, value) => { state[key] = value; render(); };
        document.getElementById('search').addEventListener('input', e => setFilter('search', e.target.value.trim().toLowerCase()));
        document.getElementById('typeFilter').addEventListener('change', e => setFilter('type', e.target.value));
        document.getElementById('sort').addEventListener('change', e => setFilter('sort', e.target.value));
        document.querySelectorAll('#statusPills button').forEach(pill => pill.addEventListener('click', () => {
            document.querySelectorAll('#statusPills button').forEach(p => {
                p.classList.toggle('btn-primary', p === pill);
                p.classList.toggle('btn-outline-secondary', p !== pill);
            });
            setFilter('status', pill.dataset.status);
        }));

        // Click a report to open it; its Reply button opens it on the thread
        const list = document.getElementById('reportList');
        list.addEventListener('click', e => {
            const reply = e.target.closest('[data-reply]');
            const item = e.target.closest('[data-id]');
            if (item && !e.target.closest('button:disabled')) openReport(item.dataset.id, !!reply);
        });
        list.addEventListener('keydown', e => {
            if (e.key === 'Enter' && e.target.matches('[data-id]')) openReport(e.target.dataset.id);
        });

        // ---- Drawer ----
        const drawerEl = document.getElementById('applicantDrawer');
        const drawer = bootstrap.Offcanvas.getOrCreateInstance(drawerEl);

        function openReport(id, showThread = false) {
            const r = byId(id);
            openId = id;
            // Opening an unread report marks it: "Awaiting Reply" if IATO wants an answer, else "Read"
            if (r.status === 'Unread') r.status = r.needs_reply ? 'Awaiting Reply' : 'Read';

            document.getElementById('drawerTitle').textContent = r.title;
            document.getElementById('drawerSender').textContent = `${r.sender} (IATO Admin)`;
            document.getElementById('drawerSent').textContent = r.sent_label;
            document.getElementById('drawerType').textContent = r.type;
            document.getElementById('previewTitle').textContent = r.title;
            document.getElementById('previewSender').textContent = r.sender;
            document.getElementById('previewDate').textContent = r.sent_label.split(' · ')[0];
            document.getElementById('previewType').textContent = r.type;
            renderPreview(r);
            renderThread(r);
            document.getElementById('replyForm').reset();
            document.getElementById('replyForm').classList.remove('was-validated');

            bootstrap.Tab.getOrCreateInstance(drawerEl.querySelector(showThread ? '#threadTab' : '[data-bs-target="#tabPreview"]')).show();
            drawer.show();
            render();
        }

        // The scholars in the report: everyone, or only those that don't match ("issues")
        function renderPreview(r) {
            const rows = SCHOLARS.filter(s => r.preview === 'all' || s.lamp_status === 'Discrepancy' || s.lamp_status === 'Not Found');
            document.getElementById('previewRows').replaceChildren(...rows.map(s => {
                const tr = document.createElement('tr');
                const note = s.lamp_status === 'Discrepancy' ? `LAMP shows ${s.lamp_record}`
                    : s.lamp_status === 'Not Found' ? 'Not in LAMP records' : '—';
                [s.name, s.type, '', note].forEach((text, i) => {
                    const td = document.createElement('td');
                    if (i === 2) {
                        const badge = document.createElement('span');
                        setBadge(badge, s.lamp_status, ...LAMP_BADGES[s.lamp_status]);
                        td.appendChild(badge);
                    } else {
                        td.textContent = text;
                    }
                    tr.appendChild(td);
                });
                return tr;
            }));
        }

        function renderThread(r) {
            document.getElementById('thread').replaceChildren(...r.thread.map(m => {
                const mine = m.from === 'lamp';
                const bubble = document.createElement('div');
                bubble.className = `rounded-3 border p-3 ${mine ? 'align-self-end text-end bg-info-subtle border-info-subtle' : 'align-self-start bg-primary-subtle border-primary-subtle'}`;
                bubble.style.maxWidth = '90%';
                bubble.innerHTML = '<div class="small fw-bold mb-1"></div><div class="small"></div><div class="small text-body-secondary mt-1"></div>';
                bubble.children[0].textContent = `${m.name} · ${mine ? 'LAMP Office' : 'IATO Admin'}`;
                bubble.children[1].textContent = m.text;
                bubble.children[2].textContent = m.at;
                return bubble;
            }));
        }

        // Sending a reply adds it to the thread and marks the report "Replied"
        document.getElementById('replyForm').addEventListener('submit', e => {
            e.preventDefault();
            const form = e.target;
            form.classList.add('was-validated');
            if (!form.checkValidity()) return;
            const r = byId(openId);
            const now = new Date();
            r.thread.push({
                from: 'lamp',
                name: @json(auth()->user()->name),
                text: document.getElementById('replyText').value.trim(),
                at: now.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) + ' · ' +
                    now.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }),
            });
            r.status = 'Replied';
            renderThread(r);
            form.reset();
            form.classList.remove('was-validated');
            bootstrap.Tab.getOrCreateInstance(document.getElementById('threadTab')).show();
            render();
            toast('Reply added to the thread (sample only — IATO isn\'t notified yet).');
        });

        render();
    </script>
@endsection
