@extends('layouts.app')

@section('title', 'iARIS — Reports')
@section('page-title', 'Official Reports')
@section('page-subtitle', 'Generate and submit admissions reports to other offices and institutional leadership')

@php
    $reports = collect($sections)->pluck('reports')->flatten(1)->keyBy('key');
@endphp

@section('content')
    {{-- Report cards, one section at a time --}}
    @foreach ($sections as $section)
        <div class="mb-3">
            <h2 class="fs-6 fw-bold mb-1">{{ $section['title'] }}</h2>
            <p class="small text-body-secondary mb-0">{{ $section['description'] }}</p>
        </div>

        <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-3 mb-4">
            @foreach ($section['reports'] as $report)
                <div class="col">
                    <div class="card border-0 border-top border-3 border-{{ $report['tone'] }} shadow-sm rounded-4 h-100">
                        <div class="card-body d-flex flex-column p-4">
                            <div class="icon-circle rounded-3 bg-{{ $report['tone'] }}-subtle text-{{ $report['tone'] }}-emphasis fs-5 d-flex align-items-center justify-content-center mb-3">
                                <i class="bi {{ $report['icon'] }}"></i>
                            </div>
                            <h3 class="fs-6 fw-bold mb-2">{{ $report['title'] }}</h3>
                            <p class="small text-body-secondary flex-grow-1">{{ $report['description'] }}</p>
                            <span class="badge rounded-pill bg-body-tertiary text-body-secondary border align-self-start mb-3 px-3 py-2">
                                <i class="bi bi-send me-1"></i> {{ $report['recipient'] }}
                            </span>
                            <div class="d-flex gap-2">
                                <button type="button" class="btn btn-light border flex-fill fw-semibold" data-open-report="{{ $report['key'] }}" data-mode="preview">
                                    <i class="bi bi-eye me-1"></i> Preview
                                </button>
                                <button type="button" class="btn btn-primary flex-fill fw-semibold" data-open-report="{{ $report['key'] }}" data-mode="generate">
                                    <i class="bi bi-lightning-charge me-1"></i> Generate
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    @endforeach

    {{-- Report history --}}
    <div class="card border-0 shadow-sm rounded-4">
        <div class="card-body p-4">
            <div class="d-flex flex-wrap align-items-start justify-content-between gap-3 mb-3">
                <div>
                    <h2 class="fs-6 fw-bold mb-1">Report Generation History</h2>
                    <p class="small text-body-secondary mb-0">Log of all reports generated by IATO Admin and Staff</p>
                </div>
                <select class="form-select w-auto" id="recipientFilter" aria-label="Filter by recipient">
                    <option value="">All Recipients</option>
                    @foreach ($reports->pluck('recipient')->unique() as $recipient)
                        <option>{{ $recipient }}</option>
                    @endforeach
                </select>
            </div>

            <div class="table-responsive">
                <table class="table table-hover align-middle mb-0">
                    <thead class="table-light">
                        <tr class="small text-uppercase text-nowrap">
                            <th class="text-body-secondary fw-bold">Report Name</th>
                            <th class="text-body-secondary fw-bold">Recipient</th>
                            <th class="text-body-secondary fw-bold">Period</th>
                            <th class="text-body-secondary fw-bold">Format</th>
                            <th class="text-body-secondary fw-bold">Generated By</th>
                            <th class="text-body-secondary fw-bold">Date &amp; Time</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="historyRows">
                        @foreach ($history as $entry)
                            @include('reports.partials.history-row', ['entry' => $entry])
                        @endforeach
                        <tr id="historyEmpty" class="d-none">
                            <td colspan="7" class="text-center text-body-secondary py-4">No reports for this recipient yet.</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {{-- A template row, copied by the script when a new (sample) report is "generated" --}}
    <template id="historyRowTemplate">
        @include('reports.partials.history-row', ['entry' => ['report' => '', 'name' => '', 'meta' => '', 'recipient' => '', 'period' => '', 'format' => '', 'by' => '', 'at' => '']])
    </template>

    {{-- One modal for both Preview and Generate --}}
    <div class="modal fade" id="reportModal" tabindex="-1" aria-labelledby="reportTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
            <div class="modal-content border-0 rounded-4 overflow-hidden">
                <div class="modal-header bg-iaris text-white border-0 p-4">
                    <div>
                        <h3 class="modal-title fs-5 fw-bold" id="reportTitle"></h3>
                        <p class="small text-white-50 mb-0" id="reportSubtitle"></p>
                    </div>
                    <button type="button" class="btn-close btn-close-white align-self-start" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body p-4">
                    {{-- Sample previews: one per report, only the chosen one is shown --}}
                    <div id="previewArea">
                        @foreach ($reports as $key => $report)
                            <div class="rounded-3 border bg-body-tertiary p-3 mb-4 d-none" data-preview="{{ $key }}">
                                <div class="small fw-bold mb-2">{{ $report['title'] }} — Sample Preview</div>
                                <div class="table-responsive">
                                    <table class="table table-sm align-middle small mb-0 bg-white">
                                        <thead>
                                            <tr class="text-uppercase text-nowrap">
                                                @foreach ($report['columns'] as $column)
                                                    <th class="text-body-secondary fw-bold">{{ $column }}</th>
                                                @endforeach
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($report['rows'] as $row)
                                                <tr>
                                                    @foreach ($row as $cell)
                                                        <td class="text-nowrap">
                                                            @if (is_array($cell))
                                                                <span class="badge rounded-pill bg-{{ $cell[1] }}-subtle text-{{ $cell[1] }}-emphasis">{{ $cell[0] }}</span>
                                                            @else
                                                                {{ $cell }}
                                                            @endif
                                                        </td>
                                                    @endforeach
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <div class="small text-body-secondary mt-2">{{ $report['note'] }}</div>
                            </div>
                        @endforeach
                    </div>

                    <div class="row g-3 mb-4">
                        <div class="col-sm-6">
                            <label for="reportPeriod" class="form-label small fw-bold text-uppercase text-body-secondary">Period Covered</label>
                            <select class="form-select" id="reportPeriod">
                                @foreach ($periods as $period)
                                    <option>{{ $period }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-sm-6">
                            <label for="reportRecipient" class="form-label small fw-bold text-uppercase text-body-secondary">Recipient Office</label>
                            <input type="text" class="form-control bg-body-tertiary" id="reportRecipient" readonly>
                        </div>
                    </div>

                    <div class="small fw-bold text-uppercase text-body-secondary mb-2">Export Format</div>
                    <div class="row g-2">
                        @foreach (['PDF' => 'bi-file-earmark-pdf', 'XLSX' => 'bi-file-earmark-excel', 'Print' => 'bi-printer'] as $format => $icon)
                            <div class="col-4">
                                <input type="radio" class="btn-check" name="reportFormat" id="format{{ $format }}" value="{{ $format }}" {{ $loop->first ? 'checked' : '' }}>
                                <label class="btn btn-outline-primary w-100 py-3" for="format{{ $format }}">
                                    <i class="bi {{ $icon }} fs-4 d-block mb-1"></i> {{ $format === 'XLSX' ? 'Excel' : $format }}
                                </label>
                            </div>
                        @endforeach
                    </div>
                </div>

                <div class="modal-footer border-0 px-4 pb-4 pt-0">
                    <button type="button" class="btn btn-light border flex-fill" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary fw-semibold flex-fill" id="generateButton">
                        <i class="bi bi-box-arrow-up-right me-1"></i> Generate &amp; Download
                    </button>
                </div>
            </div>
        </div>
    </div>

    {{-- Toast shown after "generating" a sample report --}}
    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div class="toast align-items-center border-0 text-bg-dark" id="reportToast" role="status" aria-live="polite">
            <div class="d-flex">
                <div class="toast-body" id="reportToastText"></div>
                <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        const REPORTS = @json($reports);
        const CURRENT_USER = @json(auth()->user()->name);

        const modalEl = document.getElementById('reportModal');
        const modal = bootstrap.Modal.getOrCreateInstance(modalEl);
        let currentKey = null;

        // Open the modal. "preview" shows the sample table; "generate" skips straight to the settings.
        function openReport(key, mode) {
            const report = REPORTS[key];
            currentKey = key;
            document.getElementById('reportTitle').textContent = (mode === 'generate' ? 'Generate: ' : '') + report.title;
            document.getElementById('reportSubtitle').textContent = `Recipient: ${report.recipient} · ` +
                (mode === 'preview' ? 'Sample data — configure settings below' : 'Configure before generating');
            document.getElementById('reportRecipient').value = report.recipient;
            document.querySelectorAll('[data-preview]').forEach(p => p.classList.toggle('d-none', mode !== 'preview' || p.dataset.preview !== key));
            modal.show();
        }

        document.querySelectorAll('[data-open-report]').forEach(btn =>
            btn.addEventListener('click', () => openReport(btn.dataset.openReport, btn.dataset.mode)));

        // Eye button in the history table re-opens that report's preview
        document.getElementById('historyRows').addEventListener('click', e => {
            const view = e.target.closest('[data-view-report]');
            if (view) openReport(view.dataset.viewReport, 'preview');
        });

        // Front end only: reports aren't really generated yet. Add a row to the history and say so.
        // TODO: send period + format to a backend route that builds the file.
        document.getElementById('generateButton').addEventListener('click', () => {
            const report = REPORTS[currentKey];
            const format = document.querySelector('input[name="reportFormat"]:checked').value;
            const period = document.getElementById('reportPeriod').value;
            const now = new Date();
            const stamp = now.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) + ' · ' +
                now.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });

            const row = document.getElementById('historyRowTemplate').content.firstElementChild.cloneNode(true);
            row.dataset.recipient = report.recipient;
            row.querySelector('[data-cell="name"]').textContent = report.title;
            row.querySelector('[data-cell="meta"]').textContent = 'Sample only — not saved';
            row.querySelector('[data-cell="recipient"]').textContent = report.recipient;
            row.querySelector('[data-cell="period"]').textContent = period.replace('Academic Year', 'AY');
            row.querySelector('[data-cell="format"]').textContent = format === 'Print' ? 'PRINT' : format;
            row.querySelector('[data-cell="by"]').textContent = CURRENT_USER;
            row.querySelector('[data-cell="at"]').textContent = stamp;
            row.querySelector('[data-view-report]').dataset.viewReport = currentKey;
            document.getElementById('historyRows').prepend(row);
            applyRecipientFilter();

            modal.hide();
            document.getElementById('reportToastText').textContent =
                `"${report.title}" added to the history as a sample. Real ${format === 'Print' ? 'printing' : format + ' files'} will come once the backend is connected.`;
            bootstrap.Toast.getOrCreateInstance(document.getElementById('reportToast')).show();
        });

        // Recipient filter for the history table
        function applyRecipientFilter() {
            const wanted = document.getElementById('recipientFilter').value;
            let shown = 0;
            document.querySelectorAll('#historyRows tr[data-recipient]').forEach(row => {
                const match = !wanted || row.dataset.recipient === wanted;
                row.classList.toggle('d-none', !match);
                if (match) shown++;
            });
            document.getElementById('historyEmpty').classList.toggle('d-none', shown > 0);
        }
        document.getElementById('recipientFilter').addEventListener('change', applyRecipientFilter);
    </script>
@endsection
